wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path('', views.index, name="index"),
    path('wiki/<str:title>', views.content, name="title"),
    path('search/', views.search, name="search"),
    path('create/', views.create, name="create"),
    path('wiki/<str:title>/edit/', views.edit, name="edit"),
    path('random/', views.randomPage, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import random
import markdown2

from . import util


# Checks if the title that user wants to add already exists or not.
def is_unique(title):
     if not util.get_entry(title):
          return True
     return False


class NewEntryForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"rows": "20", "cols": "100"}))
    
    # If the title already exists, application raises a validation error without saving.
    def clean_title(self):
        data = self.cleaned_data.get("title")
        
        if not is_unique(data):
             raise forms.ValidationError("Error: This page already exists.")
        return data

class EditEntryForm(forms.Form):
    edit_content = forms.CharField(widget=forms.Textarea(attrs={"rows": "20", "cols": "100"}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
    })

def content(request, title):
    if util.get_entry(title):
        return render(request, "encyclopedia/content.html", {
            "retrieve": markdown2.markdown(util.get_entry(title)),
            "name": title
                })
    else:
         return render(request, "encyclopedia/content.html", {
              "retrieve": util.get_entry(title),
              "name": title
                })
         

def search(request):
        searched = request.GET['q']
        if not util.get_entry(searched):
            matches = []
            for entry in util.list_entries():
                 if searched.lower() in entry.lower():
                      matches.append(entry)
            return render(request, "encyclopedia/search.html", {
                "searched": searched,
                "matches": matches
                })
        else:
             return HttpResponseRedirect(reverse("wiki:title", args=[searched]))
        
def create(request):
     if request.method == "GET":
        return render(request, "encyclopedia/create.html", {
           "form": NewEntryForm()
     })
     else:
        form = NewEntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            util.save_entry(title, content)
            return HttpResponseRedirect(reverse("wiki:title", args=[title]))
        else:
             return render(request, "encyclopedia/create.html", {
                  "form": form
             })

def edit(request, title):
    if request.method == "GET":
        content = util.get_entry(title)
        edit_form = EditEntryForm({"edit_content": content})
    
        return render(request, "encyclopedia/edit.html", {
             "form": edit_form,
             "title": title 
            })
    else:
         edit_form = EditEntryForm(request.POST)
         if edit_form.is_valid():
              content = edit_form.cleaned_data["edit_content"]
              util.save_entry(title, content)
              return HttpResponseRedirect(reverse("wiki:title", args=[title]))
         else:
              return render(request, "encyclopedia/edit.html", {
                 "form": edit_form  
              })

def randomPage(request):
     random_entry = random.choice(util.list_entries())
     return HttpResponseRedirect(reverse("wiki:title", args=[random_entry]))

wiki/encyclopedia/templates/encyclopedia/content.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if not retrieve %}
        Page Not Found
    {% else %}
        {{ name }}
    {% endif %}
{% endblock %}

{% block body %}
    {% if not retrieve %}
        <h1>Error : Requested page wasn't found.</h1>
    {% else %}
        <a id="edit" href="{% url 'wiki:edit' name %}">Edit This page</a>
        {{ retrieve | safe }}
    {% endif %}
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create New Page
{% endblock %}

{% block body %}
    <h1>Create New Page</h1>
    
    <form method="POST" action="{% url 'wiki:create' %}">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="save_entry">Save Entry</button>
    </form>    
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}
    <h1>Edit Page for : "{{ title }}"</h1>
    
    <form method="POST" action="{% url 'wiki:edit' title %}">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="save_entry">Save Entry</button>
    </form>   
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="wiki/{{entry}}">{{ entry }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="GET" action="{% url 'wiki:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {% if searched %}
        Search results for: {{ searched }}
    {% else %}
        Search criteria not entered.
    {% endif %}
{% endblock %}

{% block body %}
    {% if searched %}
        <h1> No match found for : "{{ searched }}"</h1>
        <h2> Listing entries containing your search criteria : </h2>
        <ul>
            {% for match in matches %}
            <li><a href="{% url 'wiki:title' match %}">{{ match }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <h1>No data entered.</h1>
    {% endif %}
{% endblock %}